### ISSUE TITLE
completion needs an inferior python process running

### ISSUE THREAD

**Issue by sac7e** [proofit404/company-anaconda#12]
There is no completion and in the status line there is an error saying `completion needs an inferior python process running`. Could you tell me how to solve this?

**Comment by proofit404** [comment]
This error has nothing related to the `company-anaconda` package. So I close this issue.

This error was triggered by `company-capf` backend, which use `complete-at-point-function` defined in the python mode. Python mode try to get completion from inferior python buffer with running interpreter in it.

This happens because `company-capf` backend was chosen instead of `company-anaconda`. This obviously occurs if your point stays inside string or comment. Company anaconda skipped in this case to make dabbrev candidates available.

Also this maybe a trouble with your Emacs configuration. If `company-anaconda` stays after `company-capf` in the `company-backends` list you will never see `anaconda-candidates`. Also `anaconda-mode` must be enable in the python buffer.

Feel free to continue this discussion here.

**Comment by sac7e** [comment]
Thank you for reply. After I checked `company-backends`, company-anaconda is not in the list as you said. It is because I use `with-eval-after-load` not `eval-after-load`. It is solved now. Thank you.

**Comment by proofit404** [comment]
Glad we solve it :smile:
